# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0023_alter_page_revision_on_delete_behaviour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('standfirst', wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='To be displayed in the list view', max_length=350)),
                ('body', wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Full body of the article')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
