# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20160116_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.ArticleCategory'),
        ),
        migrations.AlterField(
            model_name='article',
            name='external_ref',
            field=models.URLField(blank=True, null=True, verbose_name='Source URL'),
        ),
    ]
