# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20160116_2051'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='ArticlePage',
        ),
    ]
