# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0010_change_on_delete_behaviour'),
        ('articles', '0005_articlepage_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='bg_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
