# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_articlepage_bg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.ArticleCategory'),
        ),
    ]
